name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      package_name: serialtoolbox
      package_version: 0.2-1
      dirname: serialtoolbox_0.2-1
      CC: gcc-10
      CXX: g++-10

    steps:
      - name: Checkout️
        uses: actions/checkout@v2.3.1
      - name: Setup .deb Directory
        run: mkdir -p ${dirname}/usr/local/bin
      - name: Install dependencies
        run: sudo apt install qttools5-dev qttools5-dev-tools qtdeclarative5-dev
      - name: Build Package
        run: ./.github/workflows/build_deb.sh ${package_name} ${package_version}
      - name: Test install
        run: sudo dpkg -i ${dirname}.deb
      - name: Move Package into deploy dir
        run: |
          mkdir deploy
          cp ${dirname}.deb deploy/${package_name}.deb
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          BRANCH: gh-pages
          FOLDER: deploy
          CLEAN: true
