name: Unit Tests
on: [pull_request]

jobs:
  GTest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cxx: [g++-8, g++-9, g++-10, clang++-9]
        build: [Release, Debug]
    env:
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt install qtbase5-dev-tools
      - name: Set up Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
      - name: Build
        run: |
          cd build
          make -j$(nproc)
      - name: Test
        run: |
          ./build/test/Tests
